services:

  # start this container first then li-server-py, frontend whenever
  li-pgsql-db:
    container_name: li-pgsql
    image: postgres:18.1
    shm_size: 1024mb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - li_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: party

  li-server-py:
    container_name: li-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/server
    env_file:
      - ./backend/.env
    depends_on:
      - li-pgsql-db

  li-frontend-tsx:
    container_name: li-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - li_node_modules:/frontend/node_modules
    command: npm run dev -- --host
    ports:
      - 5173:5173
    
volumes:
  li_postgres_data:
  li_node_modules:


  # redis-db:
  #   container_name: redis-db
  #   image: redis:latest
  #   restart: always
  #   working_dir: /redis
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - /home/kyoko/code/fastAPI-proj/redis/:/redis