services:
  li-pgsql-dev:
    profiles: [dev, test]
    container_name: li-pgsql
    image: dhi.io/postgres:18.3-debian13
    shm_size: 1024mb
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - li_postgres_data_dev:/var/lib/postgresql
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  li-pgsql-prod:
    profiles: [prod]
    container_name: li-pgsql
    image: dhi.io/postgres:18.3-debian13
    shm_size: 1024mb
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - li_postgres_data_prod:/var/lib/postgresql
    env_file:
      - .env.prod.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  li-server-dev:
    profiles: [dev, test]
    container_name: server-java
    build:
      context: ./backend/localinference
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./backend/localinference:/server
      - maven-cache:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: ${COMPOSE_PROFILES}
    env_file:
      - .env.server
      - .env.db
    depends_on:
      li-pgsql-dev:
        condition: service_healthy
    networks:
      - backend-net

  li-server-prod:
    profiles: [prod]
    container_name: server-java
    build:
      context: ./backend/localinference
      dockerfile: Dprod.Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env.prod.server
      - .env.prod.db
    depends_on:
      li-pgsql-prod:
        condition: service_healthy
    restart: always
    networks:
      - backend-net

volumes:
  li_postgres_data_dev:
  li_postgres_data_prod:
  maven-cache:

networks:
  backend-net:
    driver: bridge
