spring.application.name=localinference
spring.profiles.active=@spring.profiles.active@

server.port=8080
socket.port=9000


# spring.data.web.pageable.default-page-size=20
# spring.data.web.pageable.max-page-size=50


# JWT
jwt.secret=${JWT_SECRET:localdevonlysecretkeyfortestingpurposesonly1234}
jwt.access-token.expiration=900000 
jwt.refresh-token.expiration=604800000


# Overriden in profiles
server.error.include-stacktrace=never


# JPA shared settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true