services:
  li-db:
    container_name: lidb
    image: dhi.io/postgres:18.3-debian13
    shm_size: 1024mb
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgsql_iman:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  # li-server:
  #   container_name: java-deb-server
  #   ports:
  #     - '127.0.0.1:8080:8080'
  #   build:
  #     context: ./local_inference # backend
  #     dockerfile: Dockerfile
  #     args:
  #       UID: 1000
  #       GID: 1000
  #   ports:
  #     - "127.0.0.1:8000:8000"
  #   volumes:
  #     - ./:/server
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     pgsql-db:
  #       condition: service_healthy
  #   networks:
  #     - backend-net

volumes:
  pgsql_iman:

networks:
  backend-net:
    driver: bridge
