"""update v1

Revision ID: 2199ddb15269
Revises: 
Create Date: 2026-03-16 19:20:11.071621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2199ddb15269'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_id',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('join_date', sa.DATE(), nullable=False),
    sa.Column('request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_pending_user_email'), 'pending_user', ['email'], unique=True)
    op.create_index(op.f('ix_pending_user_username'), 'pending_user', ['username'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('join_date', sa.DATE(), nullable=False),
    sa.Column('request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_date', sa.DATE(), nullable=False),
    sa.Column('last_login_date', sa.DATE(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'vip', 'user', name='member_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pending_user_username'), table_name='pending_user')
    op.drop_index(op.f('ix_pending_user_email'), table_name='pending_user')
    op.drop_table('pending_user')
    op.drop_table('user_id')
    # ### end Alembic commands ###